name: ml-band-gaps
channels:
  - conda-forge
dependencies:
  - pip
  - tqdm
  - numpy
  - pandas
  - pytables
  - scipy
  - scikit-learn
  - xgboost
  - matplotlib
  - pymatgen
  - phonopy
  - ipykernel
  - ipywidgets
  - ipympl
  - pandoc
  - notebook
  - jupyter_client
  - pytest
  - pytest-cov
  - pytest-xdist
  - coverage
  - autopep8
  - black
  - flake8
  - pip:
     - "--editable=git+https://github.com/materialsproject/api.git@main#egg=mp-api"
    